package com.example.model

object UiStrings {
    fun get(lang: AppLanguage, key: String): String {
        val bn = lang == AppLanguage.BANGLA
        return when (key) {
            "app_name" -> if (bn) "সানি ৪প্লেয়ার গেম" else "SANI 4Player Game"
            "app_subtitle" -> if (bn) "১০০+ অফলাইন লোকাল মাল্টিপ্লেয়ার ও বট মিনি-গেম" else "100+ Offline Local Multiplayer & Bot Mini-Games"
            "home" -> if (bn) "হোম" else "Home"
            "games" -> if (bn) "গেমসমূহ" else "Games"
            "search_hint" -> if (bn) "গেমের নাম, ক্যাটাগরি বা কীওয়ার্ড খুঁজুন..." else "Search by game name, category, or keyword..."
            "favorites" -> if (bn) "ফেভারিটস" else "Favorites"
            "favorites_only" -> if (bn) "শুধু প্রিয় গেম" else "Favorites Only"
            "categories" -> if (bn) "ক্যাটাগরি" else "Categories"
            "settings" -> if (bn) "সেটিংস" else "Settings"
            "language" -> if (bn) "ভাষা (Language)" else "Language"
            "players_supported" -> if (bn) "সমর্থিত প্লেয়ার" else "Supported Players"
            "players" -> if (bn) "প্লেয়ার" else "Players"
            "player" -> if (bn) "প্লেয়ার" else "Player"
            "bot" -> if (bn) "বট" else "Bot"
            "bots" -> if (bn) "বট" else "Bots"
            "easy" -> if (bn) "সহজ" else "Easy"
            "normal" -> if (bn) "সাধারণ" else "Normal"
            "hard" -> if (bn) "কঠিন" else "Hard"
            "start" -> if (bn) "গেম শুরু করুন" else "START MATCH"
            "pause" -> if (bn) "বিরতি" else "Pause"
            "paused" -> if (bn) "গেম বিরতি" else "GAME PAUSED"
            "resume" -> if (bn) "চালিয়ে যান" else "Resume"
            "restart" -> if (bn) "পুনরায় শুরু" else "Restart"
            "exit" -> if (bn) "প্রস্থান করুন" else "Exit to Game Selection"
            "winner" -> if (bn) "বিজয়ী!" else "WINNER!"
            "draw" -> if (bn) "ম্যাচ ড্র!" else "MATCH DRAW!"
            "game_over" -> if (bn) "গেম সমাপ্ত" else "GAME OVER"
            "replay" -> if (bn) "আবার খেলুন" else "Replay Match"
            "back_to_games" -> if (bn) "গেম তালিকায় ফিরুন" else "Back to Games"
            "select_mode" -> if (bn) "গেম মোড নির্বাচন করুন" else "Select Game Mode"
            "configure_match" -> if (bn) "ম্যাচ কনফিগারেশন" else "Configure Match"
            "bot_difficulty" -> if (bn) "বট ডিফিকাল্টি" else "Bot Difficulty"
            "how_Many_players" -> if (bn) "কতজন প্লেয়ার খেলবে?" else "Number of Local Players"
            "how_many_bots" -> if (bn) "কতটি বট প্রতিপক্ষ?" else "Number of Bot Opponents"
            "objective" -> if (bn) "লক্ষ্য ও নিয়ম" else "Objective & Rules"
            "win_condition" -> if (bn) "জয়ের শর্ত" else "Win Condition"
            "controls" -> if (bn) "কন্ট্রোল" else "Controls"
            "match_duration" -> if (bn) "ম্যাচের সময়" else "Match Duration"
            "seconds_short" -> if (bn) "সেকেন্ড" else "sec"
            "music_volume" -> if (bn) "মিউজিক ভলিউম" else "Music Volume"
            "sfx_volume" -> if (bn) "সাউন্ড ইফেক্টস ভলিউম" else "Sound Effects Volume"
            "mute_all" -> if (bn) "সব সাউন্ড মিউট করুন" else "Mute All Audio"
            "vibration" -> if (bn) "ভাইব্রেশন / হ্যাপটিক্স" else "Vibration Feedback"
            "fullscreen" -> if (bn) "ফুলস্ক্রিন মোড" else "Fullscreen Gameplay"
            "graphics_quality" -> if (bn) "গ্রাফিক্স কোয়ালিটি" else "Graphics Quality"
            "control_sensitivity" -> if (bn) "কন্ট্রোল সেন্সিটিভিটি" else "Control Sensitivity"
            "reset_favorites" -> if (bn) "ফেভারিট রিসেট করুন" else "Reset Favorites"
            "reset_settings" -> if (bn) "সেটিংস ডিফল্ট করুন" else "Reset All Settings"
            "about" -> if (bn) "অ্যাপ সম্পর্কে" else "About SANI 4Player Game"
            "app_version" -> if (bn) "সংস্করণ ১.০.০ (১০০% অফলাইন)" else "Version 1.0.0 (100% Offline Edition)"
            "about_desc" -> if (bn) "সানি ৪প্লেয়ার গেম হলো ১০৫টি ভিন্নধর্মী টপ-ডাউন ২ডি মিনি-গেমের একটি সম্পূর্ণ অফলাইন কালেকশন। একই ফোনে ২ থেকে ৪ জন বন্ধু অথবা স্মার্ট বটের বিরুদ্ধে খেলুন কোনো ইন্টারনেট বা বিজ্ঞাপন ছাড়াই।" else "SANI 4Player Game is a complete 100% offline collection of 105 unique 2D top-down mini-games. Play locally with 2–4 players on a single phone or challenge smart AI bots with zero ads and zero internet required."
            "no_games_found" -> if (bn) "কোনো গেম পাওয়া যায়নি" else "No matching games found"
            "no_favorites_yet" -> if (bn) "এখনো কোনো প্রিয় গেম যোগ করা হয়নি। যেকোনো গেমের হার্ট আইকনে ট্যাপ করুন!" else "No favorite games yet. Tap the heart icon on any game card to save it here!"
            "clear_filters" -> if (bn) "ফিল্টার মুছুন" else "Clear Filters"
            "match_summary" -> if (bn) "ম্যাচ সারাংশ" else "Match Summary"
            "player_colors" -> if (bn) "প্লেয়ার পরিচিতি ও রঙ" else "Player Colors & Identity"
            "ready_go" -> if (bn) "শুরু!" else "GO!"
            "back" -> if (bn) "পেছনে" else "Back"
            "reset_done" -> if (bn) "সফলভাবে রিসেট করা হয়েছে" else "Reset completed"
            else -> key
        }
    }
}
